import type { EntityDomain } from './types'

/**
 * The six domains Lexi is willing to name.
 *
 * They exist to disambiguate, not to classify everything: a page that matches none of
 * them simply has no domain, and every ambiguous term falls back to its first sense.
 */
export const entityDomains: EntityDomain[] = ['tech', 'finance', 'product', 'medical', 'legal', 'academic']

export const entityDomainLabels: Record<EntityDomain, string> = {
  tech: '技术工程',
  finance: '金融商业',
  product: '产品与公司',
  medical: '医学生物',
  legal: '法律合规',
  academic: '学术论文',
}

/** For the in-page dot legend and the side panel counters, where the full label does not fit. */
export const entityDomainShortLabels: Record<EntityDomain, string> = {
  tech: '技术',
  finance: '金融',
  product: '产品',
  medical: '医学',
  legal: '法律',
  academic: '学术',
}

/**
 * Mirrors `--d-*` in the site stylesheet so one domain reads the same on the landing
 * page and in the page overlay. Per DESIGN.md these values carry domain and nothing
 * else — they are never reused for state, action or severity.
 */
export const entityDomainColors: Record<EntityDomain, { ink: string, soft: string }> = {
  tech: { ink: '#1976ff', soft: '#e8f0fe' },
  finance: { ink: '#0e8f52', soft: '#e6f5ec' },
  product: { ink: '#7c5cff', soft: '#f0ecff' },
  medical: { ink: '#d9534b', soft: '#fbebea' },
  legal: { ink: '#0e8c9b', soft: '#e4f4f6' },
  academic: { ink: '#b87400', soft: '#fbf1df' },
}

export function isEntityDomain(value: unknown): value is EntityDomain {
  return typeof value === 'string' && (entityDomains as string[]).includes(value)
}

export function createDomainScores(): Record<EntityDomain, number> {
  return { tech: 0, finance: 0, product: 0, medical: 0, legal: 0, academic: 0 }
}

/**
 * Hosts that decide the domain on their own.
 *
 * Matched as suffixes, so `blog.arxiv.org` counts too. Kept deliberately short: a host
 * only earns a place here when its content is overwhelmingly one domain, because this
 * outweighs everything the page text can say.
 */
export const entityDomainHosts: Array<{ domain: EntityDomain, hosts: string[] }> = [
  {
    domain: 'tech',
    hosts: [
      'github.com',
      'gitlab.com',
      'stackoverflow.com',
      'developer.mozilla.org',
      'kubernetes.io',
      'npmjs.com',
      'pypi.org',
      'docs.rs',
      'rust-lang.org',
      'golang.org',
      'go.dev',
      'python.org',
      'nodejs.org',
      'readthedocs.io',
      'devdocs.io',
      'hacker-news.firebaseio.com',
      'news.ycombinator.com',
      'infoq.com',
      'juejin.cn',
      'csdn.net',
      'cnblogs.com',
      'segmentfault.com',
    ],
  },
  {
    domain: 'finance',
    hosts: [
      'bloomberg.com',
      'ft.com',
      'wsj.com',
      'investopedia.com',
      'marketwatch.com',
      'seekingalpha.com',
      'morningstar.com',
      'sec.gov',
      'nasdaq.com',
      'nyse.com',
      'crunchbase.com',
      'pitchbook.com',
      'eastmoney.com',
      'xueqiu.com',
      'caixin.com',
      'jrj.com.cn',
    ],
  },
  {
    domain: 'medical',
    hosts: [
      'pubmed.ncbi.nlm.nih.gov',
      'ncbi.nlm.nih.gov',
      'nih.gov',
      'who.int',
      'nejm.org',
      'thelancet.com',
      'bmj.com',
      'jamanetwork.com',
      'mayoclinic.org',
      'clinicaltrials.gov',
      'fda.gov',
      'medlineplus.gov',
      'uptodate.com',
      'medscape.com',
      'dxy.cn',
    ],
  },
  {
    domain: 'legal',
    hosts: [
      'law.cornell.edu',
      'justia.com',
      'courtlistener.com',
      'supremecourt.gov',
      'eur-lex.europa.eu',
      'uspto.gov',
      'copyright.gov',
      'ftc.gov',
      'gdpr.eu',
      'ico.org.uk',
      'pkulaw.com',
      'court.gov.cn',
    ],
  },
  {
    domain: 'academic',
    hosts: [
      'arxiv.org',
      'nature.com',
      'science.org',
      'sciencedirect.com',
      'springer.com',
      'link.springer.com',
      'ieee.org',
      'ieeexplore.ieee.org',
      'dl.acm.org',
      'jstor.org',
      'semanticscholar.org',
      'openreview.net',
      'biorxiv.org',
      'ssrn.com',
      'scholar.google.com',
      'cnki.net',
    ],
  },
  {
    domain: 'product',
    hosts: [
      'producthunt.com',
      'techcrunch.com',
      'theverge.com',
      'venturebeat.com',
      'g2.com',
      'capterra.com',
    ],
  },
]

/**
 * Marker words that vote for a domain.
 *
 * Scoring counts each distinct marker once (see `pageDomain.ts`), so a list is judged by
 * how many different markers a real page of that kind hits, not by how often one fires.
 * Words that any technical page might use — `data`, `model`, `system` — are left out on
 * purpose: a marker that matches everywhere decides nothing.
 */
export const entityDomainMarkers: Record<EntityDomain, string[]> = {
  tech: [
    'api',
    'runtime',
    'compiler',
    'deploy',
    'deployment',
    'kubernetes',
    'container',
    'docker',
    'repository',
    'commit',
    'merge request',
    'pull request',
    'endpoint',
    'middleware',
    'schema',
    'typescript',
    'javascript',
    'python',
    'rust',
    'golang',
    'backend',
    'frontend',
    'devops',
    'latency',
    'throughput',
    'concurrency',
    'async',
    'webhook',
    'sdk',
    'cli',
    'oauth',
    'jwt',
    'microservice',
    'serverless',
    'refactor',
    'stack trace',
    'dependency',
    'npm',
    'compile',
    '编译',
    '部署',
    '接口',
    '容器',
    '并发',
    '重构',
    '仓库',
    '后端',
    '前端',
    '运维',
  ],
  finance: [
    'revenue',
    'valuation',
    'investor',
    'funding round',
    'venture capital',
    'ipo',
    'ebitda',
    'margin',
    'earnings',
    'portfolio',
    'dividend',
    'liquidity',
    'hedge',
    'arbitrage',
    'yield',
    'equity stake',
    'cap table',
    'runway',
    'burn rate',
    'churn',
    'arr',
    'mrr',
    'saas metrics',
    'balance sheet',
    'cash flow',
    'shareholder',
    'acquisition',
    'merger',
    'underwriting',
    'basis point',
    'interest rate',
    'fiscal',
    'quarterly results',
    '估值',
    '融资',
    '营收',
    '毛利',
    '股东',
    '分红',
    '流动性',
    '财报',
    '市值',
    '投资人',
  ],
  product: [
    'onboarding',
    'roadmap',
    'changelog',
    'beta',
    'launch',
    'pricing tier',
    'free tier',
    'waitlist',
    'early access',
    'general availability',
    'user feedback',
    'retention',
    'feature flag',
    'release notes',
    'product manager',
    'design system',
    'user research',
    'startup',
    'founder',
    'launched today',
    'now available',
    '内测',
    '公测',
    '发布',
    '上线',
    '路线图',
    '试用',
    '订阅',
    '功能更新',
    '创始人',
  ],
  medical: [
    'patient',
    'clinical',
    'clinical trial',
    'diagnosis',
    'therapy',
    'dose',
    'dosage',
    'placebo',
    'symptom',
    'efficacy',
    'adverse event',
    'in vivo',
    'in vitro',
    'antibody',
    'protein',
    'gene expression',
    'tumor',
    'oncology',
    'cardiac',
    'immune',
    'pathogen',
    'randomized',
    'cohort study',
    'morbidity',
    'mortality',
    'prognosis',
    'biomarker',
    'fda approval',
    'pharmacokinetics',
    'contraindication',
    '临床',
    '患者',
    '疗效',
    '剂量',
    '副作用',
    '确诊',
    '病灶',
    '免疫',
    '基因',
    '疾病',
  ],
  legal: [
    'plaintiff',
    'defendant',
    'jurisdiction',
    'statute',
    'liability',
    'indemnity',
    'breach',
    'litigation',
    'compliance',
    'regulation',
    'contract',
    'clause',
    'arbitration',
    'injunction',
    'due diligence',
    'intellectual property',
    'trademark',
    'patent claim',
    'antitrust',
    'settlement',
    'subpoena',
    'testimony',
    'court ruling',
    'gdpr',
    'privacy policy',
    'terms of service',
    'warranty',
    'copyright',
    '合规',
    '条款',
    '诉讼',
    '侵权',
    '仲裁',
    '管辖',
    '被告',
    '原告',
    '判决',
    '监管',
  ],
  academic: [
    'abstract',
    'peer-reviewed',
    'peer review',
    'hypothesis',
    'methodology',
    'literature review',
    'citation',
    'preprint',
    'et al',
    'p-value',
    'statistically significant',
    'confidence interval',
    'ablation',
    'benchmark results',
    'baseline model',
    'related work',
    'we propose',
    'experimental setup',
    'reproducibility',
    'corpus',
    'annotation',
    'empirical',
    'conference paper',
    'journal',
    'doi',
    'supplementary material',
    '摘要',
    '文献',
    '实验',
    '假设',
    '显著性',
    '引用',
    '综述',
    '论文',
    '数据集',
    '基线',
  ],
}
