export const settingsStorageKey = 'touch-xxeng-heart-settings'
export const vocabularyStorageKey = 'touch-xxeng-heart-vocabulary'
export const aiCallLogsStorageKey = 'touch-xxeng-heart-ai-call-logs'
export const pageVisitLogsStorageKey = 'touch-xxeng-heart-page-visit-logs'
export const pageTranslationsStorageKey = 'touch-xxeng-heart-page-translations'
export const githubDigestStorageKey = 'touch-xxeng-heart-github-digests'
