export const settingsStorageKey = 'touch-xxeng-heart-settings'
export const vocabularyStorageKey = 'touch-xxeng-heart-vocabulary'
export const aiCallLogsStorageKey = 'touch-xxeng-heart-ai-call-logs'
export const pageVisitLogsStorageKey = 'touch-xxeng-heart-page-visit-logs'
export const pageTranslationsStorageKey = 'touch-xxeng-heart-page-translations'
export const pageTranslationMemoryStorageKey = 'touch-xxeng-heart-page-translation-memory'
export const pageTranslationActivationsStorageKey = 'touch-xxeng-heart-page-translation-activations'
export const githubDigestStorageKey = 'touch-xxeng-heart-github-digests'
export const forumDigestStorageKey = 'touch-xxeng-heart-forum-digests'
export const contentDigestStorageKey = 'touch-xxeng-heart-content-digests'
export const contentDigestLeaseStorageKey = 'touch-xxeng-heart-content-digest-leases'
/** Sync-area keys; the mirror is chunked because one sync item is capped at 8 KB. */
export const syncSettingsMetaKey = 'lexi-sync-settings-meta'
export const syncSettingsChunkPrefix = 'lexi-sync-settings-chunk-'
/** Local-only: identifies this browser profile so it can ignore its own sync writes. */
export const syncDeviceIdStorageKey = 'touch-xxeng-heart-sync-device-id'
